apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgis
  labels:
    app: postgis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgis
  template:
    metadata:
      labels:
        app: postgis
    spec:
      containers:
        - name: postgis
          image: postgis/postgis:16-3.4
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: sardb
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgis-secret
                  key: password
          volumeMounts:
            - name: postgis-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgis-data
          persistentVolumeClaim:
            claimName: postgis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgis
spec:
  selector:
    app: postgis
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
